# Generated by Django 5.1.15 on 2026-08-20 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0004_cyclonedx_schema_enrichment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countermeasurelibrarystandard",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="countermeasure_mappings",
                to="compliance.standardrequirement",
            ),
        ),
        migrations.AlterField(
            model_name="standardrequirementmapping",
            name="from_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_mappings",
                to="compliance.standardrequirement",
            ),
        ),
        migrations.AlterField(
            model_name="standardrequirementmapping",
            name="to_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_mappings",
                to="compliance.standardrequirement",
            ),
        ),
    ]
